#!/bin/bash

clear

cd /home/SERVICES/kalatori-js

# echo "start "`date`" ---" >> ___log.log

#export KALATORI_HOST="0.0.0.0:16736"
#export KALATORI_SEED="typical final fee winner cabin friend lemon today write rose coach jewel"
#export KALATORI_DESTINATION="5EqPxC7iRP6vQTsg9rwXNHsA7VqbZa7uBjj7P4YqjTvfLiiJ"
#export KALATORI_DESTINATION="1sa1P9pU4Pa6JM2nyB2vcAQw9cCxttzpovAmCwcUHZ6UxET"
#export KALATORI_REMARK="DEBUG=true;Ebala=1;public=yes"

# echo "node" >> ___log.log

/usr/bin/node ./daemon.js

# 2&>1 >> ___log.log

#echo "node" >> ___log.log

